apiVersion: apps/v1
kind: Deployment
metadata:
  name: posthog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posthog
  template:
    metadata:
      labels:
        app: posthog
    spec:
      containers:
        - name: posthog
          image: posthog/posthog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DISABLE_SECURE_SSL_REDIRECT
              value: "true"
            - name: IS_DOCKER
              value: "true"
            - name: DATABASE_URL
              value: "postgres://posthog:posthog@postgres:5432/posthog"
            - name: REDIS_URL
              value: "redis://redis:6379/"
            - name: SECRET_KEY
              value: "eca61762-d121-11ea-a390-87ad7180027c"
            - name: DEBUG
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: posthog
spec:
  selector:
    app: posthog
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
